# env and task
env:
  name: HalfCheetah-v4
  task: ""
  exp_name: ${logger.exp_name}
  n_samples_stats: 1000
  seed: 0
  backend: gym

# logger
logger:
  backend: wandb
  project_name: TOPR-RL
  exp_name: topr_expert
  group_name: null
  eval_iter: 1000
  eval_steps: 1000
  mode: online
  eval_envs: 5
  video: False

# replay buffer
replay_buffer:
  batch_size: 256
  path: "/home/sebastian/Documents/smaller_projects/TOPR-RL/torchrl_sac/collected_buffer/replay_buffer_expert.pt"
  buffer_size: 1000000
  r2g_gamma: 0.99

# optimization
optim:
  device: null
  lr: 3e-4
  weight_decay: 0.0
  gradient_steps: 100_000

# network
model:
  hidden_sizes: [256, 256]
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1

# loss
loss: 
  entropy_bonus: True

compile:
  compile: False
  compile_mode:
  cudagraphs: False